### ISSUE TITLE
Error when running it according to the README guide.  Hive3.1.1

### ISSUE THREAD

**Issue by leiwangouc** [prasanthj/culvert#1]
org.apache.hive.streaming.StreamingException: Unable to close
        at org.apache.hive.streaming.HiveStreamingConnection$TransactionBatch.close(HiveStreamingConnection.java:973)
        at org.apache.hive.streaming.HiveStreamingConnection$TransactionBatch.markDead(HiveStreamingConnection.java:833)
        at org.apache.hive.streaming.HiveStreamingConnection$TransactionBatch.<init>(HiveStreamingConnection.java:677)
        at org.apache.hive.streaming.HiveStreamingConnection$TransactionBatch.<init>(HiveStreamingConnection.java:596)
        at org.apache.hive.streaming.HiveStreamingConnection.createNewTransactionBatch(HiveStreamingConnection.java:485)
        at org.apache.hive.streaming.HiveStreamingConnection.beginNextTransaction(HiveStreamingConnection.java:466)
        at org.apache.hive.streaming.HiveStreamingConnection.beginTransaction(HiveStreamingConnection.java:507)
        at com.github.prasanthj.culvert.core.Stream.startStreamingConnection(Stream.java:66)
        at com.github.prasanthj.culvert.core.Stream.run(Stream.java:173)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.apache.hive.streaming.AbstractRecordWriter.logStats(AbstractRecordWriter.java:547)
        at org.apache.hive.streaming.AbstractRecordWriter.close(AbstractRecordWriter.java:352)
        at org.apache.hive.streaming.HiveStreamingConnection$TransactionBatch.closeImpl(HiveStreamingConnection.java:979)
        at org.apache.hive.streaming.HiveStreamingConnection$TransactionBatch.close(HiveStreamingConnection.java:970)
        ... 13 more
Stream [stream-0] died! error: Transaction batch is null. Missing beginTransaction?
org.apache.hive.streaming.StreamingException: Transaction batch is null. Missing beginTransaction?
        at org.apache.hive.streaming.HiveStreamingConnection.checkState(HiveStreamingConnection.java:497)
        at org.apache.hive.streaming.HiveStreamingConnection.write(HiveStreamingConnection.java:526)
        at com.github.prasanthj.culvert.core.Stream.run(Stream.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Closed [stream-0]. Rows committed: 0

**Comment by leiwangouc** [comment]
It is a bug of hive-streaming-3.1.1

https://issues.apache.org/jira/browse/HIVE-22393

After changing the pom dependency to 3.0.0，it works
